spring.application.name=geoportal-api

spring.datasource.url=${NEON_DATABASE_URL:jdbc:postgresql://localhost:5432/geoportal}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.open-in-view=false

server.port=8080

catalog.layers.path=classpath:catalog/layers/
wfs.base.url=https://www.geoportal.cl/geoserver
